### ISSUE TITLE
no image

### ISSUE THREAD

**Issue by fernandex00** [mykle1/MMM-Lunartic#10]
got the module working, but is not displaying image
![chrome_2018-10-15_22-55-15](https://user-images.githubusercontent.com/34770145/46990032-784d3900-d0cd-11e8-89d3-a68ae3cbc481.png)

**Comment by mykle1** [comment]
Have you modified any of the files within the module folder? The easiest thing would be to delete the MMM-Lunartic folder from your modules folder and then re clone the repo. This way you start fresh. I just updated the module anyway so you'll get the newest release. If you have any trouble then come to the MM forum and I'll help you there. It's just easier that way

**Comment by oceank82** [comment]
HEy! im running ubuntu 16.04 and I just installed this module. I dont have a picture either. I do have the information though avout the moon. what did I do wrong?
