### ISSUE TITLE
information displayed below the image of the moon

### ISSUE THREAD

**Issue by Mysh3ll** [mykle1/MMM-Lunartic#12]
Hi,

after installing and configuring this module, I have the image of the moon that appears with the updated information.
However, the information is displayed over the moon and not below, so it's not easy to read.
Can a custom.css modification suffice?
Here is my config:

```
{
            module: 'MMM-Lunartic',
            position: 'bottom_left', // Best in left, center, or right regions
            config: {
                mode: "rotating", // rotating or static
                image: "current", // animation, current, DayNight or static
                distance: "km", // miles or km
                sounds: "yes", // howling wolf, only on a full moon
                useHeader: false, // true if you want a header
                header: "Phase lunaire", // Any text you want
                maxWidth: "300px",
                animationSpeed: 0,
                rotateInterval: 15000,
            }
        },
```

**Comment by mykle1** [comment]
Make your custom.css entry this:

.MMM-Lunartic img.photo {
  margin-bottom: 0px;
}

**Comment by pociorotto** [comment]
Come posso cambiare la dimensione delle informazioni ( font ) e come posso sposare le informazioni a destra, sinistra ..Grazie

**Comment by pociorotto** [comment]
How can I change the size of the information and how can I marry the information to the right, left .. Thanks
