### ISSUE TITLE
Spostamento Titoli sotto il globo

### ISSUE THREAD

**Issue by pociorotto** [mykle1/MMM-Lunartic#16]
Salve, ho lanciato il progetto..Come posso spostare solo le informazioni sopra sotto destra e sinistra delle sole informazioni ( scritte) sotto il globo? Grazie

Hi, I launched the project ... How can I move only the information above right and left only of the information (written) under the globe? Thank you

**Comment by mykle1** [comment]
Uhhh, I answered you other issue that was in English

**Comment by pociorotto** [comment]
hello..I would like to move the right globes just a little bit because they go to cover the information of my Google Calendar events..How can I do? Thank you
