### ISSUE TITLE
MM LUNARTIC

### ISSUE THREAD

**Issue by pociorotto** [mykle1/MMM-Lunartic#17]
Il mio Globo non gira.. L'immagine e' statica e cambia solo ogni tanto l'immagine ma non ruota..Cosa posso fare? Grazie
My globe doesn't turn .. The image is static and only changes the image occasionally but doesn't rotate ... What can I do? Thank you

**Comment by mykle1** [comment]
In your config entry for Lunartic. rotateInterval: 15000, is 15 secs until the next image. You have to lower this value. A Pi will have trouble if the value is too low

EDIT:

I just realized that you must be talking about MMM-EARTH. Lunartic does not employ a rotation of the moon. However, rotateInterval: 15000, is still what you need to play with
