### ISSUE TITLE
position on the left with MMM EARTH

### ISSUE THREAD

**Issue by chassain** [mykle1/MMM-Lunartic#18]
Hello Mykle,

Sorry but i have a problem with my configuration when i'm using your module and MMM-EARTH.  I can't use right position : 
`		{
			module: "MMM-EARTH",
			position: "right",
			config: {
				mode: "Natural",
				rotateInterval: 30000,
				MaxWidth: "35%",
				MaxHeight: "35%",
				}
		},

		{
			module: 'MMM-Lunartic',
			position: 'right',                   // Best in left, center, or right regions
			config: { 
				image: "animation",
				mode: "static",                     // animation, current, DayNight or static
				distance: "km",                      // miles or km
				useHeader: false,                       // true if you want a header
				header: "",   // Any text you want
				maxWidth: "250px",
				animationSpeed: 7000,                   // updated info fades in and out
    				}
		},
`

I don't understand. Earth is on the right and lunartic on left or center

**Comment by chassain** [comment]
`		{
			module: "MMM-EARTH",
			position: "right",
			config: {
				mode: "Natural",
				rotateInterval: 30000,
				MaxWidth: "35%",
				MaxHeight: "35%",
				}
		},
		{
			module: 'MMM-Lunartic',
			position: 'right',                   // Best in left, center, or right regions
			config: { 
				image: "animation",
				mode: "static",                     // animation, current, DayNight or static
				distance: "km",                      // miles or km
				useHeader: false,                       // true if you want a header
				header: "",   // Any text you want
				maxWidth: "250px",
				animationSpeed: 7000,                   // updated info fades in and out
    				}
		},
`

**Comment by mykle1** [comment]
position: "right", is incorrect. It must be position: 'top_right' or 'bottom_right'. If you still have trouble then contact me on the forum please
