### ISSUE TITLE
Moon does not show

### ISSUE THREAD

**Issue by Bursucel** [mykle1/MMM-Lunartic#19]
Hello,

In the last couple of days,the moon icon doesn't show up anymore on "current" option. I think that it is pulled through the API from an external server. 
Is there any fix I can try ? It used to work fine.

Thanks for your help.

**Comment by mykle1** [comment]
The API for the images is under construction. Here is a temporary fix until the api comes back online.
https://forum.magicmirror.builders/topic/9193/mmm-lunartic-fixed-temporarily
