### ISSUE TITLE
Static image

### ISSUE THREAD

**Issue by Wominator** [mykle1/MMM-Lunartic#21]
Hi Mykle1!
I really appreciate your work and love your modules for the MagicMirror.
Just one small thing, in the Lunartic module, the "static" picture isn't recognized anymore. Even though I choosed "static" for "image" and "mode", the module shows the huge picture of the moon and not the "static.jpg", which I would prefer most. Anyidea, how to get the picture back? 

Regards from Berlin, Germany and thanks in advance
Womi

**Comment by mykle1** [comment]
Thank you for your kind words.

The api is currently down. The module is currently using a replacement js file that does not include using the static picture. I apologize for that. However, the api stated that April 2020 the api should be working again. As of right now it is still down but I expect it will be up soon, at least I hope so. At that time the original module.js file will resume with all options intact.

In the meantime, you can add this to your custom.css file to control the size of the huge picture of the moon. Adjust to your liking.
```
.MMM-Lunartic img.photo {
  width: 50%;                /* adjust size of moon picture */
}
```

I hope this message finds you and yours healthy.

Peace

This is copied from the api site:

This US Naval Observatory Website is undergoing modernization and will be offline starting Thursday, 24 October 2019. The expected completion of work and return of service is estimated as 30 April 2020. Please visit https://www.usno.navy.mil/USNO/about-us and submit a Requirements Form to the USNO PAO if the information you are seeking is not accessible via another means.
