### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by lbyerley** [mykle1/MMM-Lunartic#22]
@mykle1 
Hi there.

Great and easy to install module. Please could you help with advice on how to change the language to english. 
Distance from earth core and distance from earth sun are a different language. The rest are english.
Many thanks.

**Comment by ChelsieVAdams** [comment]
Experiencing the same issue. Checked my settings to make sure that ‘en’ was the language and yet the top 2 lines are not in english
Thank you

**Comment by mykle1** [comment]
@lbyerley 
@TwinBAdams 

Hi guys. Sorry about the problem. I uploaded a fix that should work. Do a git pull in the MMM-Lunartic directory. Let me know. Enjoy!

**Comment by lbyerley** [comment]
Thanks a mill. All working now. Any idea when the API is going to be up and running again ?

**Comment by mykle1** [comment]
The api gave a date of April 30, 2020 which is next week. Whether or not they go live exactly on that date leaves to be seen. I'll announce it on the forum when it resumes

**Comment by lbyerley** [comment]
Thank you for the feedback. Holding thumbs.
