### ISSUE TITLE
The image "Animation" does not work 

### ISSUE THREAD

**Issue by mkrause4** [mykle1/MMM-Lunartic#23]
My configuration looks like this:

{
        	disabled: false,
        	module: 'MMM-Lunartic',
       	 	position: 'top_left', // Best in left, center, or right regions
        	config: {
            		mode: "rotating", // rotating or static
            		image: "animation", // animation, current, DayNight or static
            		distance: "km", // miles or km
	    		sounds: "no", // howling wolf, only on a full moon
           		useHeader: false, // true if you want a header
            		header: "The Lunartic is in my head", // Any text you want
            		maxWidth: "300px",
            		animationSpeed: 10,
            		rotateInterval: 15000,
        		}
   		},

**Comment by mykle1** [comment]
Yes, I'm sorry. The animation is temporarily disabled. I had to create a fix for the module to work at all when the api went down for service. It's still not up. As soon as the api comes back online I will fix the animation option
